
# the LFS version we are currently building against
VERSION=7.5
BOOK=LFS-BOOK-$(VERSION).pdf
# the machine id file generated by vagrant up
MACHINEFILE=.vagrant/machines/default/virtualbox/id

.PHONY: all clean rebuild

# perform build
#  - runs vagrant up if necessary
#  - waits for ssh to be available
#  - initiates ansible
all: $(BOOK) $(MACHINEFILE)
ifeq ($(shell VBoxManage list runningvms | grep $(shell cat $(MACHINEFILE))),)
	vagrant up
endif
	while ! ssh -q admin@192.168.22.22 exit; do sleep 1; done
	ansible-playbook -i inventory site.yml

# ganeric clean/rebuild targets
clean:
	vagrant destroy -f
rebuild: clean all

# download the LFS book if not present
$(BOOK):
	wget http://www.linuxfromscratch.org/lfs/downloads/$(VERSION)/$(BOOK)

# rebuild the vm from the base box if bootstrap of Vagrantfile changed
$(MACHINEFILE): bootstrap.sh Vagrantfile
	vagrant destroy -f
	vagrant up
